spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin_main_service_route
          uri: lb://main-service
          predicates:
            - Path=/admin/**

        - id: users_main_service_route
          uri: lb://main-service
          predicates:
            - Path=/users/**

        - id: categories_main_service_route
          uri: lb://main-service
          predicates:
            - Path=/categories/**

        - id: events_main_service_route
          uri: lb://main-service
          predicates:
            - Path=/events/**

        - id: compilations_main_service_route
          uri: lb://main-service
          predicates:
            - Path=/compilations/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty.http.server: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, refresh  # явно включите нужные эндпоинты
  endpoint:
    gateway:
      enabled: true
      show-details: always
    refresh:
      enabled: true