grpc:
  server:
    port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.CollectorSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.UserAvroDeserializer
      group-id: my-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false