spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.enabled=true
management.endpoints.web.base-path=/actuator

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/request-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

resilience4j.circuitbreaker.configs.default.slidingWindowSize=50
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50

grpc.client.collector.address=discovery:///collector
grpc.client.collector.enableKeepAlive=true
grpc.client.collector.keepAliveWithoutCalls=true
grpc.client.collector.negotiationType=plaintext